[package]
name = "op-log"
version = "0.1.0"
authors = ["Wiktor Sikora <wiktor.sikora@kodegenix.pl>"]
edition = "2018"

[dependencies]
tracing = "0.1.21"
tracing-subscriber= "0.2.13"

slog = "2.5.2"
colored = "2.0.0"
slog-bunyan = "2.2.0"
serde = "1.0.116"
serde_derive = "1.0.116"
