[package]
name = "op-log"
version = "0.1.0"
authors = ["Wiktor Sikora <wiktor.sikora@kodegenix.pl>"]
edition = "2018"

[dependencies]
slog = "2.5.0"
slog-term = "2.4.0"
slog-async = "2.3.0"
slog-kvfilter = "0.7.0"
colored = "1.8"
