[package]
name = "op-log"
version = "0.1.0"
authors = ["Wiktor Sikora <wiktor.sikora@kodegenix.pl>"]
edition = "2018"

[dependencies]
tracing = "0.1.23"
tracing-subscriber= "0.2.15"

slog = "2.7.0"
colored = "2.0.0"
slog-bunyan = "2.3.0"
serde = "1.0.123"
serde_derive = "1.0.123"
