[package]
name = "op-rev"
version = "0.1.1"
authors = ["Jakub Chłapiński <jakub.chlapinski@kodegenix.pl>"]
workspace = ".."
edition = "2018"

[dependencies]
kg-diag = "0.4.0"
kg-tree = "0.2.0"
kg-display = "0.1.2"
kg-display-derive = "0.1.1"
kg-diag-derive = "0.4.0"
slog = "2.5.2"
git2 = "0.11.0"
serde = "1.0.104"
serde_derive = "1.0.104"

[dev-dependencies]
indoc = "0.3.4"
serde_json = "1.0.44"
serde_yaml = "0.8.11"
