[package]
name = "op-rev"
version = "0.1.1"
authors = ["Jakub Chłapiński <jakub.chlapinski@kodegenix.pl>"]
workspace = ".."
edition = "2018"

[dependencies]
kg-diag = "0.4.0"
kg-tree = "0.2.0"
kg-display = "0.1.2"
kg-display-derive = "0.1.1"
kg-diag-derive = "0.4.0"
slog = "2.5.2"
git2 = "0.13.6"
serde = "1.0.110"
serde_derive = "1.0.110"
async-trait = "0.1.36"
tokio = { version = "0.2.21"}

[dev-dependencies]
indoc = "0.3.5"
serde_json = "1.0.53"
serde_yaml = "0.8.12"
