[package]
name = "op-rev"
version = "0.1.1"
authors = ["Jakub Chłapiński <jakub.chlapinski@kodegenix.pl>"]
workspace = ".."
edition = "2018"

[dependencies]
kg-diag = "0.4.0"
kg-tree = "0.2.0"
kg-display = "0.1.2"
kg-display-derive = "0.1.1"
kg-diag-derive = "0.4.0"
slog = "2.5.2"
git2 = "0.13.8"
serde = "1.0.114"
serde_derive = "1.0.114"
async-trait = "0.1.36"
tokio = "0.2.22"

[dev-dependencies]
indoc = "1.0.2"
serde_json = "1.0.57"
serde_yaml = "0.8.13"
