language: rust
rust:
  - nightly

cache: cargo

sudo: false

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake
    sources:
      - kalakris-cmake

git:
  submodules: false

before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive

before_script:
  - cargo install --force cargo-travis
  - export PATH=$HOME/.cargo/bin:$PATH

script:
  - cargo build
  - cargo test

after_success:
  - cargo coveralls