[package]
name = "op-exec"
version = "0.1.0"
authors = ["Jakub Chłapiński <jakub.chlapinski@kodegenix.pl>"]
workspace = ".."

[dependencies]
kg-diag = "0.1.0"
kg-diag-derive = "0.1.0"
kg-display-derive = "0.1.0"
kg-utils = "0.2.3"
kg-io = "0.1.0"
kg-tree = "0.1.1"
kg-template = "0.1.0"
kg-symbol= "0.1.8"
op-model = { path = "../op-model" }
tokio = "0.1.11"
tokio-process = "0.2.3"
os_pipe = "0.8.0"
time = "0.1.40"
chrono = { version = "0.4.6", features = ["serde"] }
serde = "1.0.80"
serde_derive = "1.0.80"
serde_json = "1.0.33"
serde_yaml = "0.8.7"
toml = "0.4.8"
rmp-serde = "0.13.7"
libc = "0.2.43"
regex = "1.0.6"
uuid = "0.7.1"
daemonize = "0.3.0"
bytes = "0.4.10"
lazy_static = "1.2.0"
rand = "0.5.5"
hostname = "0.1.5"
walkdir = "2.2.6"
slog = "2.4.1"
rust-crypto = "0.2.36"
users = "0.8.0"
url = "1.7.2"
