[package]
name = "op-exec"
version = "0.1.1"
authors = ["Jakub Chłapiński <jakub.chlapinski@kodegenix.pl>"]
workspace = ".."
edition = "2018"

[dependencies]
kg-diag = "0.3.1"
kg-diag-derive = "0.3.0"
kg-display-derive = "0.1.1"
kg-utils = "0.3.1"
kg-tree = "0.1.7"
kg-template = "0.1.2"
kg-symbol= "0.1.10"
kg-lang = "0.1.1"
op-model = { version = "0.1.1", path = "../op-model" }
tokio = "0.1.22"
tokio-process = "0.2.4"
os_pipe = "0.8.1"
time = "0.1.42"
chrono = { version = "0.4.7", features = ["serde"] }
serde = "1.0.99"
serde_derive = "1.0.99"
serde_json = "1.0.40"
serde_yaml = "0.8.9"
toml = "0.5.3"
rmp-serde = "0.13.7"
libc = "0.2.62"
regex = "1.2.1"
uuid = "0.7.4"
daemonize = "0.4.1"
bytes = "0.4.12"
lazy_static = "1.4.0"
rand = "0.7.0"
hostname = "0.1.5"
walkdir = "2.2.9"
slog = "2.5.2"
users = "0.9.1"
url = "2.1.0"
git2 = "0.10.0"

[dev-dependencies]
tempfile = "3.1.0"
pretty_assertions = "0.6.1"
op-test-helpers = { version = "0.1.0", path = "../op-test-helpers" }
