[package]
name = "op-exec"
version = "0.1.0"
authors = ["Jakub Chłapiński <jakub.chlapinski@kodegenix.pl>"]
workspace = ".."
edition = "2018"

[dependencies]
kg-diag = "0.1.0"
kg-diag-derive = "0.1.0"
kg-display-derive = "0.1.0"
kg-utils = "0.2.3"
kg-io = "0.1.0"
kg-tree = "0.1.1"
kg-template = "0.1.0"
kg-symbol= "0.1.8"
op-model = { path = "../op-model" }
tokio = "0.1.20"
tokio-process = "0.2.3"
os_pipe = "0.8.1"
time = "0.1.42"
chrono = { version = "0.4.6", features = ["serde"] }
serde = "1.0.91"
serde_derive = "1.0.91"
serde_json = "1.0.39"
serde_yaml = "0.8.9"
toml = "0.5.1"
rmp-serde = "0.13.7"
libc = "0.2.55"
regex = "1.1.6"
uuid = "0.7.4"
daemonize = "0.4.1"
bytes = "0.4.12"
lazy_static = "1.3.0"
rand = "0.6.5"
hostname = "0.1.5"
walkdir = "2.2.7"
slog = "2.4.1"
rust-crypto = "0.2.36"
users = "0.9.1"
url = "1.7.2"
git2 = "0.8"
