[package]
name = "op-exec"
version = "0.1.1"
authors = ["Jakub Chłapiński <jakub.chlapinski@kodegenix.pl>"]
workspace = ".."
edition = "2018"

[dependencies]
kg-diag = "0.1.1"
kg-diag-derive = "0.1.2"
kg-display-derive = "0.1.1"
kg-utils = "0.2.4"
kg-io = "0.1.1"
kg-tree = "0.1.3"
kg-template = "0.1.2"
kg-symbol= "0.1.10"
op-model = { version = "0.1.1", path = "../op-model" }
os_pipe = "0.8.1"
time = "0.1.42"
chrono = { version = "0.4.7", features = ["serde"] }
serde = "1.0.94"
serde_derive = "1.0.94"
serde_json = "1.0.40"
serde_yaml = "0.8.9"
toml = "0.5.1"
rmp-serde = "0.13.7"
libc = "0.2.58"
regex = "1.1.8"
uuid = "0.7.4"
bytes = "0.4.12"
lazy_static = "1.3.0"
rand = "0.7.0"
hostname = "0.1.5"
walkdir = "2.2.8"
slog = "2.4.1"
users = "0.9.1"
url = "1.7.2"
git2 = "0.9.1"
rayon = "1.1.0"