[package]
name = "op-exec"
version = "0.1.0"
authors = ["Jakub Chłapiński <jakub.chlapinski@kodegenix.pl>"]
workspace = ".."

[dependencies]
kg-diag = "0.1"
kg-diag-derive = "0.1"
kg-display-derive = "0.1"
kg-utils = "0.2"
kg-io = "0.1"
kg-tree = "0.1"
kg-template = "0.1"
kg-symbol= "0.1"
op-model = { path = "../op-model" }
op-net = { path = "../op-net" }
tokio = "*"
tokio-process = "*"
os_pipe = "*"
time = "*"
chrono = { version = "*", features = ["serde"] }
serde = "*"
serde_derive = "*"
serde_json = "*"
serde_yaml = "*"
toml = "*"
rmp-serde = "*"
libc = "*"
regex = "*"
uuid = "*"
daemonize = "*"
bytes = "*"
lazy_static = "*"
rand = "*"
hostname = "*"
walkdir = "*"
slog = "2.3.3"
rust-crypto = "*"
