[package]
name = "op-exec"
version = "0.1.0"
authors = ["jchlapinski <jakub.chlapinski@kodegenix.pl>"]
workspace = ".."

[dependencies]
kg-diag = { path = "../kg-diag" }
kg-diag-derive = { path = "../kg-diag-derive" }
kg-display-derive = { path = "../kg-display-derive" }
kg-utils = { path = "../kg-utils" }
kg-io = { path = "../kg-io" }
kg-tree = { path = "../kg-tree" }
kg-template = { path = "../kg-template" }
kg-symbol= { path="../kg-symbol" }
op-model = { path = "../op-model" }
op-net = { path = "../op-net" }
lru-cache = { git = "https://github.com/jchlapinski/lru-cache.git" }
linked-hash-map = { git = "https://github.com/jchlapinski/linked-hash-map.git", features = ["serde_impl", "heapsize_impl"] }
tokio = "*"
tokio-process = "*"
os_pipe = "*"
time = "*"
chrono = { version = "*", features = ["serde"] }
serde = "*"
serde_derive = "*"
serde_json = "*"
serde_yaml = "*"
toml = "*"
rmp-serde = "*"
libc = "*"
regex = "*"
uuid = "*"
daemonize = "*"
bytes = "*"
lazy_static = "*"
rand = "*"
hostname = "*"
walkdir = "*"
slog = "2.3.3"
rust-crypto = "*"
