[package]
name = "op-exec"
version = "0.1.0"
authors = ["Jakub Chłapiński <jakub.chlapinski@kodegenix.pl>"]
workspace = ".."

[dependencies]
kg-diag = "0.1.0"
kg-diag-derive = "0.1.0"
kg-display-derive = "0.1.0"
kg-utils = "0.2.3"
kg-io = "0.1.0"
kg-tree = "0.1.1"
kg-template = "0.1.0"
kg-symbol= "0.1.8"
op-model = { path = "../op-model" }
tokio = "0.1.13"
tokio-process = "0.2.3"
os_pipe = "0.8.0"
time = "0.1.40"
chrono = { version = "0.4.6", features = ["serde"] }
serde = "1.0.81"
serde_derive = "1.0.81"
serde_json = "1.0.33"
serde_yaml = "0.8.8"
toml = "0.4.10"
rmp-serde = "0.13.7"
libc = "0.2.44"
regex = "1.1.0"
uuid = "0.7.1"
daemonize = "0.3.0"
bytes = "0.4.11"
lazy_static = "1.2.0"
rand = "0.6.1"
hostname = "0.1.5"
walkdir = "2.2.7"
slog = "2.4.1"
rust-crypto = "0.2.36"
users = "0.8.1"
url = "1.7.2"
