[package]
name = "op-core"
version = "0.1.0"
authors = ["Wiktor Sikora <wiktor.sikora@kodegenix.pl>"]
edition = "2018"

[dependencies]
kg-tree = "0.2.0"
kg-diag = "0.4.0"
kg-diag-derive = "0.4.0"
kg-display-derive = "0.1.1"
kg-utils = "0.4.0"
op-engine = { version = "0.1.1", path = "../op-engine" }
op-exec = { version = "0.1.1", path = "../op-exec" }
op-model = { path = "../op-model"}
op-rev = { version = "0.1.1", path = "../op-rev" }
tokio = { version = "0.2.21", features = ["full"] }
lazy_static = "1.4.0"
serde = "1.0.114"
async-trait = "0.1.36"
futures = { version = "0.3.5", features = ["async-await"] }
shared_child = "0.3.4"
serde_derive = "1.0.114"
serde_json = "1.0.56"
serde_yaml = "0.8.13"
toml = "0.5.6"
libc = "0.2.72"
regex = "1.3.9"
slog = "2.5.2"
chrono = "0.4.13"
