[package]
name = "op-core"
version = "0.1.0"
authors = ["Wiktor Sikora <wiktor.sikora@kodegenix.pl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.2.21", features = ["full"] }
lazy_static = "1.4.0"
serde = "1.0.110"
async-trait = "0.1.36"
tracing = "0.1"
tracing-futures = "0.2"

kg-tree = "0.2.0"
op-engine = { version = "0.1.1", path = "../op-engine" }
op-exec2 = { version = "0.1.1", path = "../op-exec2" }
op-model = { path = "../op-model"}
op-rev = { version = "0.1.1", path = "../op-rev" }
futures = {version ="0.3.5", features = ["async-await"]}
shared_child = "0.3.4"
serde_derive = "1.0.110"
serde_json = "1.0.53"
serde_yaml = "0.8.12"
toml = "0.5.6"

libc = "0.2.71"
kg-diag = "0.4.0"
kg-diag-derive = "0.4.0"
kg-display-derive = "0.1.1"
kg-utils = "0.4.0"
regex = "1.3.7"
slog = "2.5.2"
