[package]
name = "op-cli"
version = "0.1.1"
authors = ["Jakub Chłapiński <jakub.chlapinski@kodegenix.pl", "Wiktor Sikora <wiktor.sikora@kodegenix.pl>"]
workspace = ".."
edition = "2018"
default-run = "op"
build = "build.rs"

[dependencies]
kg-diag = "0.4.0"
kg-tree = "0.2.0"
kg-utils = "0.4.0"
op-exec = { version = "0.1.1", path = "../op-exec" }
op-rev = { version = "0.1.1", path = "../op-rev" }
op-log = { version = "0.1.0", path = "../op-log" }
structopt = "0.3.14"
futures = "0.3.5"
serde = "1.0.110"
serde_derive = "1.0.110"
serde_json = "1.0.53"
serde_yaml = "0.8.12"
toml = "0.5.6"
uuid = { version = "0.8.1", features = ["serde"] }
slog = "2.5.2"
url = "2.1.1"
chrono = "0.4.11"
tokio = "0.2.21"

[features]
system-tests =[]

[dev-dependencies]
op-test-helpers = { version = "*", path = "../op-test-helpers" }
pretty_assertions = "0.6.1"
console = "0.11.3"

[[bin]]
name = "op"
path = "src/main.rs"

[[bin]]
name = "op-ask"
path = "src/bin/op-ask.rs"
