[package]
name = "operon"
version = "0.1.0"
authors = ["Wiktor Sikora <wiktor.sikora@kodegenix.pl>"]
workspace = ".."

[dependencies]
op-exec = { path = "../op-exec" }
kg-diag = { path = "../kg-diag" }
op-net= { path = "../op-net" }
kg-tree= { path = "../kg-tree" }

structopt = "*"
daemonize = "*"
bytes = "*"
futures = "*"
tokio = "*"
tokio-signal = "0.2.1"
tokio-codec = "0.1.0"
tokio-uds = "0.2"

serde = "*"
serde_derive = "*"
serde_json = "*"
serde_yaml = "*"
toml = "*"
rmp-serde = "*"
uuid = { version = "*", features = ["serde"] }
chrono = { version = "*", features = ["serde"] }

linked-hash-map = { git = "https://github.com/jchlapinski/linked-hash-map.git", features = ["serde_impl", "heapsize_impl"] }


actix = "*"
actix_derive = "*"

env_logger = "0.5.13"
slog = "2.3.3"
slog-term = "2.4.0"
slog-async = "2.3.0"
slog-stdlog = "3.0.2"
slog-scope = "4.0.1"
[dev-dependencies]

[[bin]]
name = "op"
path = "src/main.rs"
