[package]
name = "op-cli"
version = "0.1.1"
authors = ["Jakub Chłapiński <jakub.chlapinski@kodegenix.pl", "Wiktor Sikora <wiktor.sikora@kodegenix.pl>"]
workspace = ".."
edition = "2018"
default-run = "op"
build = "build.rs"

[dependencies]
kg-diag = "0.2"
kg-tree = "0.1"
kg-utils = "0.3.1"
op-exec = { version = "0.1.1", path = "../op-exec" }
op-log = {path = "../op-log" }
structopt = "0.2.18"
futures = "0.1.28"
serde = "1.0.98"
serde_derive = "1.0.98"
serde_json = "1.0.40"
serde_yaml = "0.8.9"
toml = "0.5.1"
uuid = { version = "0.7.4", features = ["serde"] }
slog = "2.5.2"
url = "2.0.0"
chrono = "0.4.7"
tokio = "0.1.22"

[features]
integration-tests =[]

[dev-dependencies]
op-test-helpers = { version = "*", path = "../op-test-helpers" }

[[bin]]
name = "op"
path = "src/main.rs"

[[bin]]
name = "op-ask"
path = "src/bin/op-ask.rs"
