cargo-features = ["default-run"]

[package]
name = "op-cli"
version = "0.1.0"
authors = ["Jakub Chłapiński <jakub.chlapinski@kodegenix.pl", "Wiktor Sikora <wiktor.sikora@kodegenix.pl>"]
workspace = ".."
default-run = "op"

[dependencies]
kg-diag = "0.1"
kg-tree = "0.1"
kg-utils = "0.2"
op-exec = { path = "../op-exec" }
structopt = "0.2"
futures = "0.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml = "0.8"
toml = "0.4"
uuid = { version = "*", features = ["serde"] }
actix = "*"
actix_derive = "*"
slog = "2.3"
slog-term = "2.4"
slog-async = "2.3"

[dev-dependencies]

[[bin]]
name = "op"
path = "src/main.rs"

[[bin]]
name = "op-ask"
path = "src/bin/op-ask.rs"
