[tasks.post-build]
script = [
"cp ../target/debug/op docker/", # copy opereon executable to docker context dir
"cd docker", # cd to docker context dir
"docker build -t opereon .", # build opereon host image
"docker-compose build" # build network infrastructure defined in docker-compose.yml
]

# skip rust-fmt
[tasks.format-flow]
disabled = true

# skip tests
[tasks.test-flow]
disabled = true
