[package]
name = "rust-doc-parser"
version = "0.1.0"
authors = ["Maksymilian Ciak <maksymilian.ciak@kodegenix.pl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
