[package]
name = "op-async"
version = "0.1.1"
authors = ["Jakub Chłapiński <jakub.chlapinski@kodegenix.pl", "Wiktor Sikora <wiktor.sikora@kodegenix.pl>"]
workspace = ".."
edition = "2018"

[dependencies]
kg-utils = "0.3.1"
tokio = "0.2.0-alpha.6"
uuid = { version = "0.7.4", features = ["v1", "v3", "v4", "v5", "serde"] }
