[package]
name = "op-model"
version = "0.1.1"
authors = ["Jakub Chłapiński <jakub.chlapinski@kodegenix.pl>"]
workspace = ".."
edition = "2018"

[dependencies]
kg-diag = "0.2.0"
kg-utils = "0.2.4"
kg-tree = "0.1.4"
kg-symbol = "0.1.10"
kg-display = "0.1.2"
kg-display-derive = "0.1.1"
kg-diag = "0.1.1"
kg-diag-derive = "0.1.2"
log = "0.4.6"
libc = "0.2.58"
notify = "4.0.12"
walkdir = "2.2.8"
globset = "0.4.4"
serde = "1.0.94"
serde_derive = "1.0.94"
serde_json = "1.0.40"
serde_yaml = "0.8.9"
toml = "0.5.1"
uuid = { version = "0.7.4", features = ["serde", "v1", "v3", "v4", "v5"] }
heapsize = "0.4.2"
chrono = { version = "0.4.7", features = ["serde"] }
users = "0.9.1"
git2 = "0.9.1"
parking_lot = "0.8.0"

[dev-dependencies]
indoc = "0.3.3"
difference = "2.0.0"
