[package]
name = "op-model"
version = "0.1.0"
authors = ["Jakub Chłapiński <jakub.chlapinski@kodegenix.pl>"]
workspace = ".."

[dependencies]
kg-utils = "0.2"
kg-io = "0.1"
kg-tree = "0.1"
kg-symbol = "0.1"
log = "*"
libc = "*"
notify = "*"
walkdir = "*"
globset = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
serde_yaml = "*"
toml = "*"
uuid = { version = "*", features = ["serde", "v1", "v3", "v4", "v5"] }
heapsize = "*"
chrono = { version = "*", features = ["serde"] }
users = "0.8"
rust-crypto = "*"

[dev-dependencies]
indoc = "*"
