[package]
name = "op-model"
version = "0.1.1"
authors = ["Jakub Chłapiński <jakub.chlapinski@kodegenix.pl>"]
workspace = ".."
edition = "2018"

[dependencies]
kg-diag = "0.3.1"
kg-utils = "0.3.1"
kg-tree = "0.1.7"
kg-symbol = "0.1.10"
kg-display = "0.1.2"
kg-display-derive = "0.1.1"
kg-diag-derive = "0.3.0"
slog = "2.5.2"
libc = "0.2.62"
notify = "4.0.12"
walkdir = "2.2.9"
globset = "0.4.4"
serde = "1.0.99"
serde_derive = "1.0.99"
serde_json = "1.0.40"
serde_yaml = "0.8.9"
toml = "0.5.3"
uuid = { version = "0.7.4", features = ["serde", "v1", "v3", "v4", "v5"] }
heapsize = "0.4.2"
chrono = { version = "0.4.7", features = ["serde"] }
users = "0.9.1"
git2 = "0.10.0"
parking_lot = "0.9.0"

[dev-dependencies]
indoc = "0.3.4"
difference = "2.0.0"
tempfile = "3.1.0"
pretty_assertions = "0.6.1"
op-test-helpers = { version = "0.1.0", path = "../op-test-helpers" }
