[package]
name = "op-model"
version = "0.1.0"
authors = ["jchlapinski <jakub.chlapinski@kodegenix.pl>"]
workspace = ".."

[dependencies]
kg-utils = { path = "../kg-utils" }
kg-io = { path = "../kg-io" }
kg-tree = { path = "../kg-tree" }
kg-symbol = { path = "../kg-symbol" }
log = "*"
libc = "*"
linked-hash-map = { git = "https://github.com/jchlapinski/linked-hash-map.git", features = ["serde_impl", "heapsize_impl"] }
lru-cache = { git = "https://github.com/jchlapinski/lru-cache.git" }
notify = "*"
walkdir = "*"
globset = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
serde_yaml = "*"
toml = "*"
uuid = { version = "*", features = ["serde", "v1", "v3", "v4", "v5"] }
heapsize = "*"
chrono = { version = "*", features = ["serde"] }
users = "*"
rust-crypto = "*"

[dev-dependencies]
indoc = "*"
