# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.provider "docker" do |docker|
    docker.image   = "jdeathe/centos-ssh"
    docker.env = {
        "SSH_USER" =>"root",
    }
    docker.has_ssh = true
  end

  # use default vagrant insecure key instead of generating new one.
  config.ssh.insert_key = false
  config.ssh.username = "root"

  config.vm.provision "shell", inline: <<-SHELL
  SHELL

  config.vm.define "zeus" do |host|
    host.vm.hostname = "zeus"
    host.vm.network "private_network", ip: "192.168.33.10"
  end

  config.vm.define "ares" do |host|
    host.vm.hostname = "ares"
    host.vm.network "private_network", ip: "192.168.33.11"
  end

  config.vm.define "apollo" do |host|
    host.vm.hostname = "apollo"
    host.vm.network "private_network", ip: "192.168.33.12"
  end
end
